# -*- coding: utf-8 -*-
"""roadlength_calculate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nvU-Bg-2JwctrzMjtDm81oIPvwT-v_X7
"""

!pip install geopandas
import geopandas as gpd

road=gpd.read_file(r'/content/roads.shp')
road.crs

#Changine coordinate of raod from Geographic coordinate to Projected Coordinate system
road_proj=road.to_crs(epsg=32644)

road_proj.crs

road_proj.head()

#Calculating the road length in mtr
road_proj['road_length_m']= road_proj.length

print(road_proj.length)

#Calculating total net length of all road segments
total_length=road_proj.length.sum()

total_length_km=total_length/1000
print("Total length of all road segments(m):",total_length_km)
print("Total length of all road segments(m):",total_length_km)